services:
    bot:
        container_name: bot
        build: .
        command: 'python bot.py'
        env_file:
          - .env
        networks:
          - default
          - bugtracker
        restart: always

    redis:
        build: deploy/redis
        container_name: redis-bot
        command: redis-server redis.conf
        ports:
          - '6500:6379'
        volumes:
          - ./deploy/redis:/data
        restart: always 

volumes:
  redis:

networks:
  bugtracker:
    name: bugtracker_default
    external: true
