services:
    bot:
        container_name: bot
        build: .
        volumes:
          - .:/app
        command: 'python bot.py'
        env_file:
          - .env
        networks:
          - bugtracker
        restart: unless-stopped

networks:
  bugtracker:
    name: api_default
    external: true
