services:
    bot:
        container_name: bot
        build: .
        command: 'python bot.py'
        env_file:
          - .env
        networks:
          - bugtracker
        restart: always

networks:
  bugtracker:
    name: bugtracker_default
    external: true
