name: Deliver

run-name: Deliver telegram bot to the VPS

on: workflow_dispatch

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure .env
        run: |
          cat << EOF > .env
          BOT_TOKEN = ${{ secrets.BOT_TOKEN }}
          API_BASE_URL =  ${{ secrets.API_BASE_URL }}
          POSTGRES_HOST = ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PASSWORD = ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_PORT = ${{ secrets.POSTGRES_PORT }}
          POSTGRES_USER = ${{ secrets.POSTGRES_USER }}
          POSTGRES_DB = ${{ secrets.POSTGRES_DB }}
          REDIS_HOST = ${{ secrets.REDIS_HOST }}
          REDIS_USER = ${{ secrets.REDIS_USER }}
          REDIS_PASSWORD = ${{ secrets.REDIS_PASSWORD }}
          EOF

      - name: Copy repo to the VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "*"
          target: tgbot/
